//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EmbResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmbResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApp1.EmbResources", typeof(EmbResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.VCLibs
        ///Microsoft.NET
        ///Microsoft.WindowsStore
        ///Microsoft.WindowsCalculator
        ///1527c705-839a-4832-9118-54d4Bd6a0c89
        ///c5e2524a-ea46-4f67-841f-6a9465d9d515
        ///E2A4F912-2574-4A75-9BB0-0D023378592B
        ///F46D4000-FD22-4DB4-AC8E-4E1DDDE828FE
        ///InputApp
        ///Microsoft.AAD.BrokerPlugin
        ///Microsoft.AccountsControl
        ///Microsoft.AsyncTextService
        ///Microsoft.BioEnrollment
        ///Microsoft.CredDialogHost
        ///Microsoft.ECApp
        ///Microsoft.LockApp
        ///Microsoft.MicrosoftEdge
        ///Microsoft.MicrosoftEdgeDevToolsClient
        ///Microsoft.PPIProjection
        ///Micro [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string hiddenapps {
            get {
                return ResourceManager.GetString("hiddenapps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.VCLibs
        ///Microsoft.NET
        ///Microsoft.WindowsStore
        ///Microsoft.WindowsCalculator
        ///Microsoft.3DBuilder.
        /// </summary>
        internal static string hiddenpapps {
            get {
                return ResourceManager.GetString("hiddenpapps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;LayoutModificationTemplate xmlns:defaultlayout=&quot;http://schemas.microsoft.com/Start/2014/FullDefaultLayout&quot; xmlns:start=&quot;http://schemas.microsoft.com/Start/2014/StartLayout&quot; Version=&quot;1&quot; xmlns=&quot;http://schemas.microsoft.com/Start/2014/LayoutModification&quot;&gt;
        ///  &lt;LayoutOptions StartTileGroupCellWidth=&quot;6&quot; /&gt;
        ///  &lt;DefaultLayoutOverride&gt;
        ///    &lt;StartLayoutCollection&gt;
        ///      &lt;defaultlayout:StartLayout GroupCellWidth=&quot;6&quot; /&gt;
        ///    &lt;/StartLayoutCollection&gt;
        ///  &lt;/DefaultLayoutOverride&gt;
        ///&lt;/LayoutModificationTemplate&gt;.
        /// </summary>
        internal static string LayoutModification {
            get {
                return ResourceManager.GetString("LayoutModification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Config xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;checkTest&gt;
        ///    &lt;int&gt;0&lt;/int&gt;
        ///    &lt;int&gt;0&lt;/int&gt;
        ///    &lt;int&gt;0&lt;/int&gt;
        ///    &lt;int&gt;0&lt;/int&gt;
        ///    &lt;int&gt;0&lt;/int&gt;
        ///    &lt;int&gt;0&lt;/int&gt;
        ///    &lt;int&gt;0&lt;/int&gt;
        ///    &lt;int&gt;0&lt;/int&gt;
        ///    &lt;int&gt;0&lt;/int&gt;
        ///    &lt;int&gt;0&lt;/int&gt;
        ///    &lt;int&gt;0&lt;/int&gt;
        ///    &lt;int&gt;0&lt;/int&gt;
        ///    &lt;int&gt;0&lt;/int&gt;
        ///    &lt;int&gt;0&lt;/int&gt;
        ///    &lt;int&gt;0&lt;/int&gt;
        ///    &lt;int&gt;0&lt;/int&gt;
        ///    &lt;int&gt;0&lt;/int&gt;
        ///    &lt;int&gt;0&lt;/int&gt;
        ///    &lt;int&gt;0&lt;/int&gt;
        ///    &lt;int&gt;0&lt;/int&gt;
        ///    &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MinimalSettings {
            get {
                return ResourceManager.GetString("MinimalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Config xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;checkTest&gt;
        ///    &lt;int&gt;0&lt;/int&gt;
        ///    &lt;int&gt;0&lt;/int&gt;
        ///    &lt;int&gt;0&lt;/int&gt;
        ///    &lt;int&gt;0&lt;/int&gt;
        ///    &lt;int&gt;0&lt;/int&gt;
        ///    &lt;int&gt;0&lt;/int&gt;
        ///    &lt;int&gt;0&lt;/int&gt;
        ///    &lt;int&gt;1&lt;/int&gt;
        ///    &lt;int&gt;1&lt;/int&gt;
        ///    &lt;int&gt;0&lt;/int&gt;
        ///    &lt;int&gt;0&lt;/int&gt;
        ///    &lt;int&gt;1&lt;/int&gt;
        ///    &lt;int&gt;0&lt;/int&gt;
        ///    &lt;int&gt;1&lt;/int&gt;
        ///    &lt;int&gt;1&lt;/int&gt;
        ///    &lt;int&gt;1&lt;/int&gt;
        ///    &lt;int&gt;0&lt;/int&gt;
        ///    &lt;int&gt;1&lt;/int&gt;
        ///    &lt;int&gt;0&lt;/int&gt;
        ///    &lt;int&gt;0&lt;/int&gt;
        ///    &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RecommendedSettings {
            get {
                return ResourceManager.GetString("RecommendedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Config xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;checkTest&gt;
        ///    &lt;int&gt;0&lt;/int&gt;
        ///    &lt;int&gt;0&lt;/int&gt;
        ///    &lt;int&gt;0&lt;/int&gt;
        ///    &lt;int&gt;0&lt;/int&gt;
        ///    &lt;int&gt;0&lt;/int&gt;
        ///    &lt;int&gt;0&lt;/int&gt;
        ///    &lt;int&gt;0&lt;/int&gt;
        ///    &lt;int&gt;0&lt;/int&gt;
        ///    &lt;int&gt;0&lt;/int&gt;
        ///    &lt;int&gt;0&lt;/int&gt;
        ///    &lt;int&gt;0&lt;/int&gt;
        ///    &lt;int&gt;0&lt;/int&gt;
        ///    &lt;int&gt;0&lt;/int&gt;
        ///    &lt;int&gt;0&lt;/int&gt;
        ///    &lt;int&gt;0&lt;/int&gt;
        ///    &lt;int&gt;0&lt;/int&gt;
        ///    &lt;int&gt;0&lt;/int&gt;
        ///    &lt;int&gt;0&lt;/int&gt;
        ///    &lt;int&gt;0&lt;/int&gt;
        ///    &lt;int&gt;0&lt;/int&gt;
        ///    &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RemoveAllSettings {
            get {
                return ResourceManager.GetString("RemoveAllSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///; Created by: Shawn Brink
        ///; Created on: August 8th 2015
        ///; Updated on: August 5th 2018
        ///; Tutorial: https://www.tenforums.com/tutorials/14312-restore-windows-photo-viewer-windows-10-a.html
        ///
        ///
        ///[HKEY_CLASSES_ROOT\Applications\photoviewer.dll\shell\open]
        ///&quot;MuiVerb&quot;=&quot;@photoviewer.dll,-3043&quot;
        ///
        ///[HKEY_CLASSES_ROOT\Applications\photoviewer.dll\shell\open\command]
        ///@=hex(2):25,00,53,00,79,00,73,00,74,00,65,00,6d,00,52,00,6f,00,6f,00,74,00,25,\
        ///  00,5c,00,53,00,79,00,73,00 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Restore_Windows_Photo_Viewer_ALL_USERS {
            get {
                return ResourceManager.GetString("Restore_Windows_Photo_Viewer_ALL_USERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///; Created by: Shawn Brink
        ///; Created on: August 8th 2015
        ///; Updated on: August 5th 2018
        ///; Tutorial: https://www.tenforums.com/tutorials/14312-restore-windows-photo-viewer-windows-10-a.html
        ///
        ///
        ///
        ///[HKEY_CLASSES_ROOT\jpegfile\shell\open\DropTarget]
        ///&quot;Clsid&quot;=-
        ///
        ///[HKEY_CLASSES_ROOT\pngfile\shell\open\DropTarget]
        ///&quot;Clsid&quot;=-
        ///
        ///[-HKEY_CLASSES_ROOT\Applications\photoviewer.dll\shell\open]
        ///
        ///[-HKEY_CLASSES_ROOT\PhotoViewer.FileAssoc.Bitmap]
        ///
        ///[-HKEY_CLASSES_ROOT\PhotoView [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Undo_Restore_Windows_Photo_Viewer_ALL_USERS {
            get {
                return ResourceManager.GetString("Undo_Restore_Windows_Photo_Viewer_ALL_USERS", resourceCulture);
            }
        }
    }
}
